### ISSUE TITLE
[Bug] Unable to create dialog for transform

### ISSUE THREAD

**Issue by remidub** [atolcd/hop-gis-plugins#14]
**What happened:**
Unable to create dialog for transform

**What you expected to happen:**
Launch a dialog for transform

**Steps to reproduce:**
- Create a new pipeline
- Add a GIS Transform, "Geometry Information" for example
- Edit Transform
- Hop prompts an error dialog : Error creating dialog, with the following message : 
```
InvocationTargetException: 
Root cause: NoSuchMethodError: 'void org.apache.hop.ui.pipeline.transform.BaseTransformDialog.<init>(org.eclipse.swt.widgets.Shell, org.apache.hop.core.variables.IVariables, org.apache.hop.pipeline.transform.BaseTransformMeta, org.apache.hop.pipeline.PipelineMeta, java.lang.String)'
```

**Anything else we need to know?**
Java stack trace :
```trace
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.getTransformDialog(HopGuiPipelineTransformDelegate.java:159)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:189)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3366)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:2208)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:97)
	at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0(GuiContextUtil.java:182)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4099)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3715)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:476)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:354)
Caused by: java.lang.NoSuchMethodError: 'void org.apache.hop.ui.pipeline.transform.BaseTransformDialog.<init>(org.eclipse.swt.widgets.Shell, org.apache.hop.core.variables.IVariables, org.apache.hop.pipeline.transform.BaseTransformMeta, org.apache.hop.pipeline.PipelineMeta, java.lang.String)'
	at com.atolcd.hop.pipeline.transforms.gisfileinput.GisFileInputDialog.<init>(GisFileInputDialog.java:113)
	at com.atolcd.hop.pipeline.transforms.gisgeometryinfo.GisGeometryInfoMeta.getDialog(GisGeometryInfoMeta.java:219)
	... 20 more
```

I have this issue on both Windows 10 & 11, and JDK 17 or 21.

**Environment:**
* Hop: 2.10.0
* Hop GIS Plugins: [1.3.0](https://github.com/atolcd/hop-gis-plugins/releases/tag/v1.3.0)
* JVM: OpenJDK 17 (Microsoft build)
* OS: Windows 10 & 11

**Any suggested solutions?**

**If the bug  is approved, would you be willing to submit a PR?**

No, to be honest, i don't think i have the super power to resolve this issue 😄

**Comment by cvagner** [comment]
Thanks for report @remidub.

I reproduced with the same version on Ubuntu `24.04` and `OpenJDK Temurin-17.0.12+7`.
I've just compiled a new version with `2.10.0` Hop dependencies (vs  `2.10.0-SNAPSHOT` for `1.3.0`) and it seems to work.

**Comment by darbonc** [comment]
Ok for me !  Thanks Charly

**Comment by cvagner** [comment]
Great news :+1:

**Comment by remidub** [comment]
It works,
thank you very much for your responsiveness ;)
